baseURL: https://sirupsen.com
languageCode: en-us
title: Sirupsen.com
enableEmoji: true
enableRobotsTXT: true
author:
  name: "Simon HÃ¸rup Eskildsen"
  email: simon@sirupsen.com
permalinks:
  post: /:filename
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 2
  goldmark:
    renderer:
      unsafe: true
